-- insert brand
INSERT INTO `brands` (`BRANDID`, `BRANDNAME`) VALUES (DEFAULT, 'ceiling'), (DEFAULT, 'wall'), (DEFAULT, 'lamp'), (DEFAULT, 'outdoor'), (DEFAULT, 'fan'), (DEFAULT, 'accents');
-- insert products
INSERT INTO `products`(`PRODUCTID`,`PRODUCTNAME`,`DETAIL`,`QUANTITY`,`STATUS`,`BRANDID`,`PRICE`,`SALEPRICE`,`CRTUSER`,`CRTDATE`,`MDFUSER`,`MDFDATE`,`SOURCE`) VALUES
(DEFAULT,'BRIGHTON TAPERED POLISHED STAINLESS STEEL PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'sale',1,499.00,199.00,NULL,NULL,NULL,NULL,'cl1.jpg'),
(DEFAULT,'BRIO BLACKENED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,399.00,NULL,NULL,NULL,NULL,NULL,'cl2.jpg'),
(DEFAULT,'BRIO POLISHED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'sale',1,399.00,299.00,NULL,NULL,NULL,NULL,'cl3.jpg'),
(DEFAULT,'COPA TIERED NATURAL RATTAN PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,499.00,NULL,NULL,NULL,NULL,NULL,'cl4.jpg'),
(DEFAULT,'EXPOSIOR INDOOR/OUTDOOR BLACK PENDANT LIGHT MODEL 017','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,299.00,NULL,NULL,NULL,NULL,NULL,'cl5.jpg'),
(DEFAULT,'HAKKA CONICAL RATTAN PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,400.00,NULL,NULL,NULL,NULL,NULL,'cl7.jpg'),
(DEFAULT,'HAMMERED BRASS SHALLOW DOME PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,399.00,NULL,NULL,NULL,NULL,NULL,'cl8.jpg'),
(DEFAULT,'LAMINA POLISHED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,449.00,NULL,NULL,NULL,NULL,NULL,'cl9.jpg'),
(DEFAULT,'LANI WHITE PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',1,449.00,NULL,NULL,NULL,NULL,NULL,'cl10.jpg'),
(DEFAULT,'BRIO POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',2,269.00,NULL,NULL,NULL,NULL,NULL,'w7.jpg'),
(DEFAULT,'CYPRESS CHAMPAGNE DOUBLE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'sale',2,379.00,179.00,NULL,NULL,NULL,NULL,'w8.jpg'),
(DEFAULT,'GRAZIANO INDOOR/OUTDOOR TRAVERTINE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',2,299.00,NULL,NULL,NULL,NULL,NULL,'w10.jpg'),
(DEFAULT,'ALDUS BLACK AND POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',2,229.00,NULL,NULL,NULL,NULL,NULL,'w3.jpg'),
(DEFAULT,'ALDUS IVORY AND POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'bestseller',2,229.00,NULL,NULL,NULL,NULL,NULL,'w4.jpg'),
(DEFAULT,'BECKER POLISHED BRASS WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'sale',2,199.00,99.00,NULL,NULL,NULL,NULL,'w5.jpg'),
(DEFAULT,'BRIO BLACKENED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',2,269.00,NULL,NULL,NULL,NULL,NULL,'w6.jpg'),
(DEFAULT,'SABINE POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'bestseller',2,199.00,NULL,NULL,NULL,NULL,NULL,'w13.jpg'),
(DEFAULT,'SABINE BLACKENED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'bestseller',2,199.00,NULL,NULL,NULL,NULL,NULL,'w14.jpg'),
(DEFAULT,'SOPORTE BLACKENED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,399.00,NULL,NULL,NULL,NULL,NULL,'l1.jpg'),
(DEFAULT,'SOPORTE POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,399.00,NULL,NULL,NULL,NULL,NULL,'l2.jpg'),
(DEFAULT,'BEAU BLACK TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,249.00,NULL,NULL,NULL,NULL,NULL,'l3.jpg'),
(DEFAULT,'BEAU POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,249.00,NULL,NULL,NULL,NULL,NULL,'l4.jpg'),
(DEFAULT,'BIANCA MARBLE TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,269.00,NULL,NULL,NULL,NULL,NULL,'l5.jpg'),
(DEFAULT,'CRINKLE POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,369.00,NULL,NULL,NULL,NULL,NULL,'l6.jpg'),
(DEFAULT,'ELEONORA MARBLE TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'sale',3,999.00,799.00,NULL,NULL,NULL,NULL,'l7.jpg'),
(DEFAULT,'EXPOSIOR POLISHED BRASS AND WALNUT TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',3,369.00,NULL,NULL,NULL,NULL,NULL,'l8.jpg'),
(DEFAULT,'EXPOSIOR INDOOR/OUTDOOR BLACK PENDANT LIGHT MODEL 017','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,299.00,NULL,NULL,NULL,NULL,NULL,'od1.jpg'),
(DEFAULT,'GRAZIANO INDOOR/OUTDOOR TRAVERTINE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,299.00,NULL,NULL,NULL,NULL,NULL,'od2.jpg'),
(DEFAULT,'RONDA INDOOR/OUTDOOR BLACK FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,199.00,NULL,NULL,NULL,NULL,NULL,'od3.jpg'),
(DEFAULT,'RONDA INDOOR/OUTDOOR MATTE BLACK WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,149.00,NULL,NULL,NULL,NULL,NULL,'od4.jpg'),
(DEFAULT,'RONDA INDOOR/OUTDOOR POLISHED BRASS FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,199.00,NULL,NULL,NULL,NULL,NULL,'od5.jpg'),
(DEFAULT,'RONDA INDOOR/OUTDOOR BLACK FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',4,199.00,NULL,NULL,NULL,NULL,NULL,'od6.jpg'),
(DEFAULT,'5 BROWN WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,191.00,NULL,NULL,NULL,NULL,NULL,'f1.jpg'),
(DEFAULT,'3 BROWN WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,80.00,NULL,NULL,NULL,NULL,NULL,'f2.jpg'),
(DEFAULT,'5 BLACK WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,191.00,NULL,NULL,NULL,NULL,NULL,'f3.jpg'),
(DEFAULT,'3 BROWN WINGS FAN PREMIUM','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,91.00,NULL,NULL,NULL,NULL,NULL,'f4.jpg'),
(DEFAULT,'5 BROWN LEAF WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,200.00,NULL,NULL,NULL,NULL,NULL,'f5.jpg'),
(DEFAULT,'5 WHITE WINGS FA','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',5,191.00,NULL,NULL,NULL,NULL,NULL,'f9.jpg'),
(DEFAULT,'BALL CANDLES SET OF 2','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,12.95,NULL,NULL,NULL,NULL,NULL,'ha1.jpg'),
(DEFAULT,'BLACK TWISTED TAPER CANDLES SET OF 2','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,4.95,NULL,NULL,NULL,NULL,NULL,'ha2.jpg'),
(DEFAULT,'BRIX GOLDEN BLACK MARBLE INCENSE BURNER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,39.95,NULL,NULL,NULL,NULL,NULL,'ha3.jpg'),
(DEFAULT,'CINQ LARGE MULTI WHITE TAPER CANDLE HOLDER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,199.00,NULL,NULL,NULL,NULL,NULL,'ha4.jpg'),
(DEFAULT,'DREAMER IN LONDON CEDARWOOD AND VANILLA CANDLE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,65.00,NULL,NULL,NULL,NULL,NULL,'ha5.jpg'),
(DEFAULT,'FALCON METAL INCENSE BURNER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,'avaiable',6,69.95,NULL,NULL,NULL,NULL,NULL,'ha6.jpg')

    

