-- insert brand
INSERT INTO `brands` (`BRANDID`, `BRANDNAME`) VALUES (NULL, 'ceiling'), (NULL, 'wall'), (NULL, 'lamp'), (NULL, 'outdoor'), (NULL, 'fan'), (NULL, 'accents')
-- insert products
INSERT INTO `products`(`PRODUCTID`,`PRODUCTNAME`,`DETAIL`,`QUANTITY`,`STATUS`,`BRANDID`,`PRICE`,`CRTUSER`,`CRTDATE`,`MDFUSER`,`MDFDATE`,`SOURCE`) VALUES(NULL,'BRIGHTON TAPERED POLISHED STAINLESS STEEL PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,499.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl1.jpg'),
(NULL,'BRIO BLACKENED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,399.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl2.jpg'),
(NULL,'BRIO POLISHED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,399.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl3.jpg'),
(NULL,'COPA TIERED NATURAL RATTAN PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,499.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl4.jpg'),
(NULL,'EXPOSIOR INDOOR/OUTDOOR BLACK PENDANT LIGHT MODEL 017','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,299.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl5.jpg'),
(NULL,'HAKKA CONICAL RATTAN PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,400.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl7.jpg'),
(NULL,'HAMMERED BRASS SHALLOW DOME PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,399.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl8.jpg'),
(NULL,'LAMINA POLISHED BRASS PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,449.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl9.jpg'),
(NULL,'LANI WHITE PENDANT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,1,449.00,NULL,NULL,NULL,NULL,'assets/img/lightType/ceiling/cl10.jpg'),
(NULL,'BRIO POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,269.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w7.jpg'),
(NULL,'CYPRESS CHAMPAGNE DOUBLE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,379.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w8.jpg'),
(NULL,'GRAZIANO INDOOR/OUTDOOR TRAVERTINE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,299.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w10.jpg'),
(NULL,'ALDUS BLACK AND POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,229.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w3.jpg'),
(NULL,'ALDUS IVORY AND POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,229.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w4.jpg'),
(NULL,'BECKER POLISHED BRASS WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w5.jpg'),
(NULL,'BRIO BLACKENED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,269.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w6.jpg'),
(NULL,'SABINE POLISHED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w13.jpg'),
(NULL,'SABINE BLACKENED BRASS ARTICULATING WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,2,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Wall/w14.jpg'),
(NULL,'SOPORTE BLACKENED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,399.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l1.jpg'),
(NULL,'SOPORTE POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,399.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l2.jpg'),
(NULL,'BEAU BLACK TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,249.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l3.jpg'),
(NULL,'BEAU POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,249.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l4.jpg'),
(NULL,'BIANCA MARBLE TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,269.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l5.jpg'),
(NULL,'CRINKLE POLISHED BRASS TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,369.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l6.jpg'),
(NULL,'ELEONORA MARBLE TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,999.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l7.jpg'),
(NULL,'EXPOSIOR POLISHED BRASS AND WALNUT TABLE LAMP','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,3,369.00,NULL,NULL,NULL,NULL,'assets/img/lightType/Lamp/l8.jpg'),
(NULL,'EXPOSIOR INDOOR/OUTDOOR BLACK PENDANT LIGHT MODEL 017','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,299.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od1.jpg'),
(NULL,'GRAZIANO INDOOR/OUTDOOR TRAVERTINE WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,299.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od2.jpg'),
(NULL,'RONDA INDOOR/OUTDOOR BLACK FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od3.jpg'),
(NULL,'RONDA INDOOR/OUTDOOR MATTE BLACK WALL SCONCE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,149.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od4.jpg'),
(NULL,'RONDA INDOOR/OUTDOOR POLISHED BRASS FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od5.jpg'),
(NULL,'RONDA INDOOR/OUTDOOR BLACK FLUSH MOUNT LIGHT','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,4,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/outdoor/od6.jpg'),
(NULL,'5 BROWN WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,191.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f1.jpg'),
(NULL,'3 BROWN WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,80.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f2.jpg'),
(NULL,'5 BLACK WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,191.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f3.jpg'),
(NULL,'3 BROWN WINGS FAN PREMIUM','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,91.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f4.jpg'),
(NULL,'5 BROWN LEAF WINGS FAN','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,200.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f5.jpg'),
(NULL,'5 WHITE WINGS FA','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,5,191.00,NULL,NULL,NULL,NULL,'assets/img/lightType/fan/f9.jpg'),
(NULL,'BALL CANDLES SET OF 2','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,12.95,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha1.jpg'),
(NULL,'BLACK TWISTED TAPER CANDLES SET OF 2','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,4.95,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha2.jpg'),
(NULL,'BRIX GOLDEN BLACK MARBLE INCENSE BURNER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,39.95,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha3.jpg'),
(NULL,'CINQ LARGE MULTI WHITE TAPER CANDLE HOLDER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,199.00,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha4.jpg'),
(NULL,'DREAMER IN LONDON CEDARWOOD AND VANILLA CANDLE','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,65.00,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha5.jpg'),
(NULL,'FALCON METAL INCENSE BURNER','Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',10,1,6,69.95,NULL,NULL,NULL,NULL,'assets/img/lightType/acess/ha6.jpg')

    

